<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201031_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=50)),
                ('date_announced', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
=======
# Generated by Django 3.1.2 on 2020-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201031_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=50)),
                ('date_announced', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
>>>>>>> 7804fdbc8beb87c0011895981248dcd449f93126
