# Generated by Django 3.1.2 on 2020-10-31 13:27

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
