# Generated by Django 3.1.2 on 2020-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201031_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports',
            field=models.CharField(max_length=300),
        ),
    ]
