# Generated by Django 3.1.2 on 2020-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201031_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
