# Generated by Django 3.1.2 on 2020-11-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_plasmacontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmacontact',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='plasmacontact',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_to', to='base.profile'),
        ),
    ]
