# Generated by Django 3.1.2 on 2020-11-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20201101_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmacontact',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
