# Generated by Django 3.1.2 on 2020-11-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201101_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, default='Tirupati', max_length=50, null=True),
        ),
    ]
